### ISSUE TITLE
Can you fix it for supporting VS2015?

### ISSUE THREAD

**Issue by techcap** [reloZid/vs-filtersync#1]
Can you fix it for supporting VS2015?

**Comment by mjaun** [comment]
I tried to add VS2015 support today.

It's working, but it broke VS2013 support because of a problem described here:
https://social.msdn.microsoft.com/Forums/en-US/d47bfe90-19bb-4c0c-9f36-74ff60eb490d/vcproject-interface-targeting-multiple-versions?forum=vsx

I will create separate projects to support both versions.

**Comment by mjaun** [comment]
Done!
